export const projects = [
  {
    id: 1,
    year: "2025",
    category: "Web 2",
    industry: "Finance",
    title: "Bluremit",
    description: "A User-centered Bureau de Change (BDC) App Integrating Multiple Agent Networks",
    info: "Bluremit is a fintech and currency exchange platform that lets users compare real-time rates and securely book transactions at a network of verified Bureau de Change (BDC) agents. It provides a standardized exchange interface and will give users the easy possibility to find the best prices and complete their forex trades with transparency and convenience...",
    imageSrc: "/bluremit.svg",
    link: "#",
    company: "Blumen Tech",
    headquarters: "Abuja, Nigeria",
    website: "Not available",
    revenue: "Not available",
    founded: "2020",
    role: "Software Engineer",
    duration: "2020 - Present",
    tools: "React Native, TypeScript, Expo, Xcode, Git, GitHub, Eas, Swagger",
    teamMember: [
      {
        id: 1,
        name: "Ibrahim Muritala",
        position: "Frontend Engineer",
        avatarSrc: "/avatar.svg",
      },
      {
        id: 2,
        name: "Manuel Emeka",
        position: "Backend Engineer",
        avatarSrc: "/manuel.jpeg",
      },
    ],
    details:
      "I worked as the lead product designer on this project, collaborating with Emmanuel, a senior backend developer whom I onboarded to join me in bringing this idea to life.",
    highlights: [
      {
        id: 1,
        imgSrc: "/highlight1.svg",
        detail: "User interface with wallet account deposits to Bluremit User or External bank account ",
      },
      {
        id: 2,
        imgSrc: "/highlight2.svg",
        detail: "User interface with exchange screen showing flow for user to create buy/sell orders",
      },
      {
        id: 3,
        imgSrc: "/highlight3.svg",
        detail: "User interface with wallet top-up via bluremit agent",
      },
      {
        id: 4,
        imgSrc: "/highlight4.svg",
        detail: "User interface showing QR Code generation for agent to scan and complete transaction",
      },
    ],
  },
  {
    id: 2,
    year: "2025",
    category: "Web 3",
    industry: "Finance",
    title: "Ultra",
    description: "A User-Centric Fintech Super-App Fusing Traditional Banking with Decentralized Finance (DeFi)",
    info: "The Ultra app is a pioneering fusion of Web2 and Web3 financial services, providing a unified platform for managing both traditional and digital assets. It seamlessly integrates conventional banking features with decentralized finance (DeFi) capabilities, eliminating the need for multiple, disconnected applications.",
    imageSrc: "/ultra.svg",
    link: "#",
  },

  {
    id: 3,
    year: "2025",
    category: "Web 3",
    industry: "Finance",
    title: "Ultra Website/Dashboard",
    description: "The Ultra Admin Dashboard: A Centralized Command Center for the Fintech Super-App",
    info: "The Ultra Admin Dashboard is a comprehensive, web-based command center designed to oversee and manage the entire ecosystem of the Ultra fintech super-app. It provides administrators with granular control over the platform's fusion of Web2 and Web3 activities, from user management to financial settlement.",
    imageSrc: "/ultra-web.png",
    link: "#",
  },
  {
    id: 4,
    year: "2025",
    category: "Web 2",
    industry: "Non-Profit",
    title: "Chats",
    description: "Transforming Global Aid Distribution with Unprecedented Transparency and Trust",
    info: "CHATS is building the future of trustworthy humanitarian aid. It empowers NGOs with a platform that turns transparency into their greatest asset, enabling them to attract more funding by verifiably proving the efficiency and impact of their cash and voucher programs. It is bridging the trust gap between donors and recipients.",
    imageSrc: "/chats2.svg",
    link: "#",
  },
  {
    id: 6,
    year: "2025",
    category: "Web 2",
    industry: "Healthcare",
    title: "Saffron Wellcare",
    description: "Saffron Wellcare: Streamlining Pharmacy Operations for Enhanced Patient Care",
    info: "Saffron Wellcare is an all-in-one pharmacy management solution designed to bring clarity and control to pharmacy operations. The platform replaces fragmented processes with a seamlessly integrated system, turning complex data into actionable insights.",
    imageSrc: "/saffron.svg",
    link: "#",
  },
  {
    id: 5,
    year: "2025",
    category: "Web 3",
    industry: "Finance",
    title: "Chainkeeping",
    description: "A simplified user centered preoder system, aimed at simplifying preoder of smart door handles",
    info: "The Stacks ecosystem is growing at a bullish pace. With about 10 protocols & communities, 19 partners & integrations, 12 tools and utilities, and about 27 dApps are currently built on the ecosystem. Stacks ecosystem is becoming a significant player in the decentralized market and web3 as a whole.",
    imageSrc: "/susmo.svg",
    link: "#",
  },
  // Add more project objects as needed
]
